spring:
  jpa:
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  issuer: merong2969
  secret_key: qpwoeirut019234



logging:
  level:
    org.hibernate.type: trace
    com.app: debug